database-owner:
  login: simplifier
  password: ${DB_PASSWORD}
  host: "%"
error-level: onGrant
databases:
  - ${DB_PREFIX}
  - ${DB_PREFIX}_content
  - ${DB_PREFIX}_keyvalue
  - ${DB_PREFIX}_session
  - ${DB_PREFIX}_jsonstore
  - ${DB_PREFIX}_wf_rt
  - ${DB_PREFIX}_wf_dt